### PR TITLE
Env

### PR DESCRIPTION
**Pull request by appelskrutt34**

### CODE REVIEW

**Comment by appelskrutt34** [comment]
@mjovanc @TechyGuy17 New env variables. Changed the names to VITE_HUGIN_API and VITE_PROMETHEUS_API

**Comment by mjovanc** [comment]
@TechyGuy17 Can you add these to Ansible?

**Comment by TechyGuy17** [comment]
Just add them to provision_vps or something else needed?

**Comment by mjovanc** [comment]
@TechyGuy17 In the role for the monitor in `docker_container` should be enough as you did earlier.

**Comment by TechyGuy17** [comment]
Okay!

**Pull request merged**
